# Generated by Django 5.2.1 on 2026-03-12 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workboard', '0002_taskchecklistitem_studentavailability_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='must_change_password',
            field=models.BooleanField(default=False),
        ),
    ]
