# Generated by Django 5.2.1 on 2026-03-13 13:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workboard', '0004_alter_task_assigned_to_taskattachment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='additional_assignees',
            field=models.ManyToManyField(blank=True, limit_choices_to={'role': 'student_worker'}, related_name='collaborative_tasks', to=settings.AUTH_USER_MODEL),
        ),
    ]
