# Generated by Django 5.2.1 on 2026-03-13 14:35

from django.db import migrations, models


def populate_board_order(apps, schema_editor):
    Task = apps.get_model("workboard", "Task")
    status_values = [choice[0] for choice in Task._meta.get_field("status").choices]
    for status in status_values:
        tasks = list(Task.objects.filter(status=status).order_by("due_date", "-created_at", "pk"))
        for index, task in enumerate(tasks, start=1):
            task.board_order = index
            task.save(update_fields=["board_order"])


def clear_board_order(apps, schema_editor):
    Task = apps.get_model("workboard", "Task")
    Task.objects.update(board_order=None)


class Migration(migrations.Migration):

    dependencies = [
        ("workboard", "0005_task_additional_assignees"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="board_order",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.RunPython(populate_board_order, clear_board_order),
    ]
