# Generated by Django 5.2.1 on 2026-03-13 16:05

from django.db import migrations, models


def copy_checklist_positions(apps, schema_editor):
    TaskChecklistItem = apps.get_model("workboard", "TaskChecklistItem")
    for item in TaskChecklistItem.objects.all().order_by("sort_order", "id"):
        item.position = item.sort_order
        item.save(update_fields=["position"])


def reverse_checklist_positions(apps, schema_editor):
    TaskChecklistItem = apps.get_model("workboard", "TaskChecklistItem")
    for item in TaskChecklistItem.objects.all().order_by("position", "id"):
        item.sort_order = item.position
        item.save(update_fields=["sort_order"])


class Migration(migrations.Migration):

    dependencies = [
        ("workboard", "0006_task_board_order"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="taskchecklistitem",
            options={"ordering": ["position", "id"]},
        ),
        migrations.AddField(
            model_name="taskchecklistitem",
            name="position",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.RunPython(copy_checklist_positions, reverse_checklist_positions),
        migrations.RemoveField(
            model_name="taskchecklistitem",
            name="completed_at",
        ),
        migrations.RemoveField(
            model_name="taskchecklistitem",
            name="is_completed",
        ),
        migrations.RemoveField(
            model_name="taskchecklistitem",
            name="sort_order",
        ),
    ]
