# Generated by Django 5.2.1 on 2026-03-13 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workboard", "0007_taskchecklistitem_position"),
    ]

    operations = [
        migrations.AddField(
            model_name="taskchecklistitem",
            name="is_completed",
            field=models.BooleanField(default=False),
        ),
    ]
