# Generated by Django 5.2.1 on 2026-03-13 17:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("workboard", "0008_taskchecklistitem_is_completed"),
    ]

    operations = [
        migrations.CreateModel(
            name="TaskEstimateFeedback",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("raw_message", models.TextField(blank=True)),
                ("task_title", models.CharField(blank=True, max_length=255)),
                ("original_estimated_minutes", models.PositiveIntegerField(blank=True, null=True)),
                ("corrected_estimated_minutes", models.PositiveIntegerField()),
                ("source", models.CharField(blank=True, max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("corrected_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="estimate_feedback_entries", to=settings.AUTH_USER_MODEL)),
                ("task", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="estimate_feedback", to="workboard.task")),
            ],
            options={"ordering": ["-created_at"]},
        ),
    ]
