# Generated by Django 5.2.1 on 2026-03-13 18:10

from django.db import migrations


def merge_assigned_into_new(apps, schema_editor):
    Task = apps.get_model("workboard", "Task")
    Task.objects.filter(status="assigned").update(status="new")


def reverse_merge_assigned_into_new(apps, schema_editor):
    Task = apps.get_model("workboard", "Task")
    Task.objects.filter(status="new", assigned_to__isnull=False).update(status="assigned")


class Migration(migrations.Migration):

    dependencies = [
        ("workboard", "0009_taskestimatefeedback"),
    ]

    operations = [
        migrations.RunPython(merge_assigned_into_new, reverse_merge_assigned_into_new),
    ]
