# Generated by Django 5.2.1 on 2026-03-17 15:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workboard', '0012_user_assignable_to_tasks'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recurringtasktemplate',
            options={'ordering': ['display_order', 'next_run_date', 'title', 'pk']},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['board_order', 'due_date', '-created_at']},
        ),
        migrations.AlterField(
            model_name='recurringtasktemplate',
            name='assign_to',
            field=models.ForeignKey(blank=True, limit_choices_to={'role__in': ['student_worker', 'student_supervisor']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recurring_templates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='task',
            name='additional_assignees',
            field=models.ManyToManyField(blank=True, limit_choices_to={'role__in': ['student_worker', 'student_supervisor']}, related_name='collaborative_tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('supervisor', 'Supervisor'), ('student_supervisor', 'Student Supervisor'), ('student_worker', 'Student Worker')], default='student_worker', max_length=32),
        ),
    ]
