# Generated by Django 5.2.1 on 2026-03-17 16:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workboard', '0013_alter_recurringtasktemplate_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurringtasktemplate',
            name='additional_assignees',
            field=models.ManyToManyField(blank=True, limit_choices_to={'role__in': ['student_worker', 'student_supervisor']}, related_name='additional_recurring_templates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recurringtasktemplate',
            name='rotate_additional_assignee',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='rotate_additional_assignee',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='rotating_additional_assignee',
            field=models.ForeignKey(blank=True, limit_choices_to={'role__in': ['student_worker', 'student_supervisor']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rotating_collaborative_tasks', to=settings.AUTH_USER_MODEL),
        ),
    ]
