# Generated by Django 5.2.1 on 2026-03-17 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workboard', '0014_recurringtasktemplate_additional_assignees_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentworkerprofile',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
