# Generated by Django 5.2.1 on 2026-03-18 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workboard', '0015_alter_studentworkerprofile_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurringtasktemplate',
            name='scheduled_end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recurringtasktemplate',
            name='scheduled_start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentavailability',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentavailability',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='scheduled_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='scheduled_end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='scheduled_start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
