# Generated by Django 5.2.1 on 2026-03-18 13:46

import django.db.models.deletion
from datetime import datetime, time, timedelta
from django.conf import settings
from django.db import migrations, models


def backfill_student_availability_blocks(apps, schema_editor):
    StudentAvailability = apps.get_model('workboard', 'StudentAvailability')
    StudentAvailabilityBlock = apps.get_model('workboard', 'StudentAvailabilityBlock')

    for availability in StudentAvailability.objects.all():
        if availability.start_time and availability.end_time:
            StudentAvailabilityBlock.objects.create(
                availability=availability,
                start_time=availability.start_time,
                end_time=availability.end_time,
                position=1,
            )
            continue

        if not availability.hours_available:
            continue

        total_minutes = int(float(availability.hours_available) * 60)
        if total_minutes <= 0 or total_minutes % 30 != 0:
            continue

        start_value = time(9, 0)
        end_value = (datetime.combine(datetime.today(), start_value) + timedelta(minutes=total_minutes)).time()
        StudentAvailabilityBlock.objects.create(
            availability=availability,
            start_time=start_value,
            end_time=end_value,
            position=1,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('workboard', '0016_recurringtasktemplate_scheduled_end_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentAvailabilityBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('position', models.PositiveSmallIntegerField(default=1)),
                ('availability', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='workboard.studentavailability')),
            ],
            options={
                'ordering': ['availability__weekday', 'position', 'start_time', 'end_time', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='StudentScheduleOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('override_date', models.DateField()),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_schedule_overrides', to=settings.AUTH_USER_MODEL)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_overrides', to='workboard.studentworkerprofile')),
            ],
            options={
                'ordering': ['override_date', 'profile__display_name'],
                'unique_together': {('profile', 'override_date')},
            },
        ),
        migrations.CreateModel(
            name='StudentScheduleOverrideBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('position', models.PositiveSmallIntegerField(default=1)),
                ('schedule_override', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='workboard.studentscheduleoverride')),
            ],
            options={
                'ordering': ['schedule_override__override_date', 'position', 'start_time', 'end_time', 'pk'],
            },
        ),
        migrations.RunPython(backfill_student_availability_blocks, migrations.RunPython.noop),
    ]
