# Generated by Django 5.2.1 on 2026-03-18 18:45

from django.conf import settings
from django.db import migrations, models


def backfill_rotating_additional_assignees(apps, schema_editor):
    Task = apps.get_model("workboard", "Task")
    RecurringTaskTemplate = apps.get_model("workboard", "RecurringTaskTemplate")
    through_model = Task.rotating_additional_assignees.through
    db_alias = schema_editor.connection.alias

    Task.objects.using(db_alias).filter(
        rotate_additional_assignee=True,
        rotating_additional_assignee_count=0,
    ).update(rotating_additional_assignee_count=1)
    RecurringTaskTemplate.objects.using(db_alias).filter(
        rotate_additional_assignee=True,
        rotating_additional_assignee_count=0,
    ).update(rotating_additional_assignee_count=1)

    for task in Task.objects.using(db_alias).exclude(rotating_additional_assignee_id__isnull=True):
        through_model.objects.using(db_alias).get_or_create(
            task_id=task.pk,
            user_id=task.rotating_additional_assignee_id,
        )


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("workboard", "0017_studentavailabilityblock_studentscheduleoverride_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="recurringtasktemplate",
            name="rotating_additional_assignee_count",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="task",
            name="rotating_additional_assignee_count",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="task",
            name="rotating_additional_assignees",
            field=models.ManyToManyField(blank=True, limit_choices_to={"role__in": ["student_worker", "student_supervisor"]}, related_name="rotating_collaborative_task_memberships", to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(backfill_rotating_additional_assignees, noop_reverse),
    ]
