# Generated by Django 5.2.1 on 2026-03-19 19:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workboard', '0018_recurringtasktemplate_rotating_additional_assignee_count_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskAuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_title', models.CharField(max_length=255)),
                ('action', models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('status_changed', 'Status Changed'), ('note_added', 'Note Added'), ('attachment_added', 'Attachment Added'), ('checklist_updated', 'Checklist Updated'), ('deleted', 'Deleted'), ('recurring_run', 'Recurring Run')], max_length=32)),
                ('summary', models.CharField(max_length=255)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_audit_events', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to='workboard.task')),
            ],
            options={
                'ordering': ['-created_at', '-pk'],
            },
        ),
    ]
