# Generated by Django 5.2.1 on 2026-03-23 13:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workboard', '0019_taskauditevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleAdjustmentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_date', models.DateField()),
                ('note', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('applied', 'Applied'), ('declined', 'Declined')], default='pending', max_length=16)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applied_override', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applied_schedule_adjustment_requests', to='workboard.studentscheduleoverride')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_adjustment_requests', to='workboard.studentworkerprofile')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_adjustment_requests', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_schedule_adjustment_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['status', 'requested_date', '-created_at', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='ScheduleAdjustmentRequestBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('position', models.PositiveSmallIntegerField(default=1)),
                ('schedule_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='workboard.scheduleadjustmentrequest')),
            ],
            options={
                'ordering': ['schedule_request__requested_date', 'position', 'start_time', 'end_time', 'pk'],
            },
        ),
    ]
