# Generated by Django 5.2.1 on 2026-03-27 11:58

import django.db.models.deletion
from django.db import migrations, models


def backfill_task_schedule_blocks(apps, schema_editor):
    Task = apps.get_model("workboard", "Task")
    TaskScheduleBlock = apps.get_model("workboard", "TaskScheduleBlock")
    blocks = []
    for task in Task.objects.exclude(scheduled_date__isnull=True).exclude(scheduled_start_time__isnull=True).exclude(scheduled_end_time__isnull=True).iterator():
        blocks.append(
            TaskScheduleBlock(
                task_id=task.pk,
                work_date=task.scheduled_date,
                start_time=task.scheduled_start_time,
                end_time=task.scheduled_end_time,
                position=1,
            )
        )
    if blocks:
        TaskScheduleBlock.objects.bulk_create(blocks, batch_size=500)


class Migration(migrations.Migration):

    dependencies = [
        ('workboard', '0020_scheduleadjustmentrequest_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskScheduleBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('position', models.PositiveSmallIntegerField(default=1)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_blocks', to='workboard.task')),
            ],
            options={
                'ordering': ['work_date', 'position', 'start_time', 'end_time', 'pk'],
            },
        ),
        migrations.RunPython(backfill_task_schedule_blocks, migrations.RunPython.noop),
    ]
