# Generated by Django 5.2.1 on 2026-03-30 19:37

import django.db.models.deletion
from django.db import migrations, models


def backfill_default_team(apps, schema_editor):
    Team = apps.get_model("workboard", "Team")
    User = apps.get_model("workboard", "User")
    Task = apps.get_model("workboard", "Task")
    RecurringTaskTemplate = apps.get_model("workboard", "RecurringTaskTemplate")
    ScheduleAdjustmentRequest = apps.get_model("workboard", "ScheduleAdjustmentRequest")

    default_team, _ = Team.objects.get_or_create(
        name="General",
        defaults={"description": "Default team for existing TaskForge data."},
    )
    User.objects.filter(team__isnull=True).update(team=default_team)
    Task.objects.filter(team__isnull=True).update(team=default_team)
    RecurringTaskTemplate.objects.filter(team__isnull=True).update(team=default_team)
    ScheduleAdjustmentRequest.objects.filter(team__isnull=True).update(team=default_team)


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("workboard", "0021_taskscheduleblock"),
    ]

    operations = [
        migrations.CreateModel(
            name="Team",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=120, unique=True)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name", "pk"],
            },
        ),
        migrations.AddField(
            model_name="recurringtasktemplate",
            name="team",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="recurring_templates", to="workboard.team"),
        ),
        migrations.AddField(
            model_name="scheduleadjustmentrequest",
            name="team",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="schedule_adjustment_requests", to="workboard.team"),
        ),
        migrations.AddField(
            model_name="task",
            name="team",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="tasks", to="workboard.team"),
        ),
        migrations.AddField(
            model_name="user",
            name="team",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="members", to="workboard.team"),
        ),
        migrations.RunPython(backfill_default_team, noop_reverse),
    ]
