# Generated by Django 5.2.1 on 2026-04-13 15:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workboard', '0023_remove_studentworkerprofile_max_hours_per_day'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkerTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='worker_tags', to='workboard.team')),
            ],
            options={
                'ordering': ['name', 'pk'],
                'unique_together': {('team', 'name')},
            },
        ),
        migrations.AddField(
            model_name='recurringtasktemplate',
            name='required_worker_tags',
            field=models.ManyToManyField(blank=True, related_name='recurring_templates', to='workboard.workertag'),
        ),
        migrations.AddField(
            model_name='studentworkerprofile',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='workers', to='workboard.workertag'),
        ),
        migrations.AddField(
            model_name='task',
            name='required_worker_tags',
            field=models.ManyToManyField(blank=True, related_name='tasks', to='workboard.workertag'),
        ),
    ]
