# Generated by Django 5.2.1 on 2026-08-04 14:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workboard', '0024_workertag_recurringtasktemplate_required_worker_tags_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlackoutDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('label', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_blackout_dates', to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blackout_dates', to='workboard.team')),
            ],
            options={
                'ordering': ['date', 'pk'],
                'unique_together': {('team', 'date')},
            },
        ),
    ]
