# Generated by Django 5.2.1 on 2026-08-24 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workboard', '0025_blackoutdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskauditevent',
            name='action',
            field=models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('status_changed', 'Status Changed'), ('note_added', 'Note Added'), ('attachment_added', 'Attachment Added'), ('checklist_updated', 'Checklist Updated'), ('deleted', 'Deleted'), ('recurring_run', 'Recurring Run'), ('handed_off', 'Handed Off')], max_length=32),
        ),
    ]
