# Generated by Django 5.2.1 on 2026-09-03 12:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workboard', '0026_alter_taskauditevent_action'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecurringTemplateScheduleBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.PositiveSmallIntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('position', models.PositiveSmallIntegerField(default=1)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_blocks', to='workboard.recurringtasktemplate')),
            ],
            options={
                'ordering': ['weekday', 'position', 'start_time', 'end_time', 'pk'],
            },
        ),
    ]
