# Generated by Django 5.2.1 on 2026-09-03 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workboard', '0027_recurringtemplatescheduleblock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('supervisor', 'Supervisor'), ('student_supervisor', 'Student Manager'), ('student_worker', 'Student Worker')], default='student_worker', max_length=32),
        ),
    ]
