# Generated by Django 5.2.1 on 2026-09-16 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workboard', '0028_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurringtasktemplate',
            name='first_run_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
