# Generated by Django 5.2.1 on 2026-09-17 20:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workboard', '0029_recurringtasktemplate_first_run_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecurringTemplateChecklistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('position', models.PositiveIntegerField(default=0)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_items', to='workboard.recurringtasktemplate')),
            ],
            options={
                'ordering': ['position', 'id'],
            },
        ),
    ]
